### PR TITLE
Add support for the UIAA grading scale

### PR DESCRIPTION
**Pull request by l4u532**
UIAA is the dominant grading scale in Central Europe. Grades are mostly stated in Arabic numerals (e.g. "7+") instead of Roman numerals (e.g. "VII+"), that's why I switched over to Arabic. This should add full functionality for UIAA, but is also a prerequisite for https://github.com/OpenBeta/openbeta-graphql/pull/252.

### CODE REVIEW

**Comment by vnugent** [comment]
@l4u532  thank you for adding UIAA support.  Can you check why tests are failing?

**Comment by l4u532** [comment]
> @l4u532 thank you for adding UIAA support. Can you check why tests are failing?

I wanted to start with a quick fix. But I decided to add full functionality for the UIAA grading system to sandbag, before https://github.com/OpenBeta/openbeta-graphql/pull/252 can be merged.

**Comment by l4u532** [comment]
> @l4u532 thank you for adding UIAA support. Can you check why tests are failing?



> > @l4u532 thank you for adding UIAA support. Can you check why tests are failing?
> 
> I wanted to start with a quick fix. But I decided to add full functionality for the UIAA grading system to sandbag, before [OpenBeta/openbeta-graphql#252](https://github.com/OpenBeta/openbeta-graphql/pull/252) can be merged.

@vnugent expanded PR with full UIAA support

**Comment by vnugent** [comment]
@l4u532 thank you for your help. `@openbeta/sandbag@0.036` has been published.

@all-contributors add @l4u532 for code & ideas

**Pull request merged**
