### PR TITLE
slash grades should have integer scores

### PR DESCRIPTION
**Pull request by johncalvinroberts**
Possible tentative fix for: https://github.com/OpenBeta/sandbag/issues/137

### CODE REVIEW

**Comment by musoke** [comment]
I suggest two changes here:
- round the top and bottom of the range in opposite directions
- add some tests

**Comment by johncalvinroberts** [comment]
@musoke updated according to your suggested implementation. Thank you so much for the guidance!

After updating, some tests (integration tests?) in `readme.ts` were failing due to hardcoded non-integer return values. This caused me to notice that `French` scale implementation was also suffering from the same defect, and could potentially return non-integer score values for slash grades. So, I updated with the same logic, assuming slash grades to be _exclusive_ of adjacent grades in the french scale. Is that a correct?

Also, definitely LMK if there are any other issues with my implementation and I'll try to fix.

**Comment by musoke** [comment]
> After updating, some tests (integration tests?) in `readme.ts` were failing due to hardcoded non-integer return values. This caused me to notice that `French` scale implementation was also suffering from the same defect, and could potentially return non-integer score values for slash grades. So, I updated with the same logic, assuming slash grades to be _exclusive_ of adjacent grades in the french scale. Is that a correct?

Yes, now that you point it out, this this is going to be an issue with all the scales. Maybe you could define a function to do this check for each scales.  Or I can add it to other scales in a followup.

**Comment by johncalvinroberts** [comment]
> > After updating, some tests (integration tests?) in `readme.ts` were failing due to hardcoded non-integer return values. This caused me to notice that `French` scale implementation was also suffering from the same defect, and could potentially return non-integer score values for slash grades. So, I updated with the same logic, assuming slash grades to be _exclusive_ of adjacent grades in the french scale. Is that a correct?
> 
> Yes, now that you point it out, this this is going to be an issue with all the scales. Maybe you could define a function to do this check for each scales. Or I can add it to other scales in a followup.

Updated accordingly with a `getRoundedScoreTuple` utility func, and applied to other grade scales which could return a tuple with high/low based on adjacent scores. Is that what you had in mind? @musoke 

It doesn't feel super DRY, but then again that seems to be the running style in this codebase? The enclosing `getScore` function is mostly the same across grade scales, so I also tried to follow roughly the same level of abstraction. Let me know if stylistically there is anything I should know 😄

**Comment by musoke** [comment]
That looks good to me.  

Yes, there is a  lot of repetition due to the adhoc evolution of sandbag.  The special cases in methods like `getScore` do make this a little tricky.  I would welcome refactors to improve this.

**Pull request merged**
