### PR TITLE
[npm publish]

### PR DESCRIPTION
**Pull request by musoke**

### CODE REVIEW

**Comment by musoke** [comment]
@vnugent , I noticed that although the action has been tagging new versions, they haven't been released.  I think this is the way to do it.  Not sure if you need to approve it?

**Comment by vnugent** [comment]
You can merge the PR.  I think the only check it does is looking for the string `[npm publish]` in the PR's title.
https://github.com/OpenBeta/sandbag/blob/develop/.github/workflows/auto-version-bump.yml#L32

**Comment by musoke** [comment]
Ok - could you approve this PR, please?

**Comment by musoke** [comment]
Thanks! To be clear: I don't have permission to merge in this repo without reviews.

**Comment by vnugent** [comment]
> Thanks! To be clear: I don't have permission to merge in this repo without reviews.

Ah gotcha.  I've removed the "Require approvals" rule.  I thought as a maintainer you can override that check and merge.

Screenshot 2023-06-03 at 10 10 41 AM

**Comment by musoke** [comment]
Thanks!

**Pull request merged**
